A/A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]

A/accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/',views.UserFollowView.as_view(), name= 'follow'),
    path('unfollow/<int:user_id>/  ', views.UserUnfollowView.as_view(), name = 'unfollow'),
    path('editprofile/',views.EditProfileView.as_view(),name = 'edit_profile'),
]

A/home/urls.py
from django.urls import path
from . import views



app_name='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.PostView.as_view(),name='detail'),
    path('post/delete/<int:post_id>/<slug:post_slug>/',views.DeletePostView.as_view(),name='delete'),
    path('post/update/<int:post_id>/',views.UpdatePostView.as_view(),name='update'),
    path('post/create/',views.CreatePostView.as_view(),name='create'),
    path('reply/<int:post_id>/<int:comment_id>/',views.ReplyPostView.as_view(),name = 'add_reply'),
    path('like/<int:post_id>/',views.LikePostView.as_view(),name = 'like_post'),
]

A/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Relation(models.Model):
    from_user = models.ForeignKey(User,on_delete= models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete= models.CASCADE, related_name= 'following')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.from_user} followed {self.to_user}'
class Profile(models.Model):
    user = models.OneToOneField(User ,on_delete = models.CASCADE)
    age = models.PositiveIntegerField(default = 0)
    bio = models.TextField(null = True,blank = True)

A/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from .models import Profile

class UserRegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password',widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='confirm password',widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']  # Use square brackets
        user_exists = User.objects.filter(email=email).exists()
        if user_exists:
            raise ValidationError('Email already exists. Please use a different email.')

        return email

    def clean_username(self):  # Corrected method name
        username = self.cleaned_data['username']  # Use square brackets
        username_exists = User.objects.filter(username=username).exists()
        if username_exists:
            raise ValidationError('Username already exists. Please choose a different one.')

        return username

    def clean(self):
        cd=super().clean()
        p1= cd.get('password1')
        p2= cd.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError('password must match')
        return cd
class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class EditProfileForm(forms.ModelForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = Profile
        fields = ('age','bio')


    

A/accounts/views.py
from django.shortcuts import render,redirect
from django.views import View
from . import forms
from .models import Relation
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_view

class UserRegisterView(View):
    form_class=forms.UserRegisterForm
    template_name = 'accounts/register.html'
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)


    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            User.objects.create_user(username=cd['username'],email=cd['email'],password=cd['password1'])
            messages.success(request,'your account Registered successfully:)))','success')
            return redirect('home:home')
        return render(request,self.template_name,{'form':form})

    def get(self,request):
        form=self.form_class()
        return render(request,self.template_name,{'form':form})
class UserLoginView(View):
    form_class = forms.UserLoginForm
    template_name = 'accounts/login.html'

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request,'your account logged in successfully:)))','success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            messages.error(request,'your password or username is not correct:(((','danger')
        return render(request,self.template_name,{'form':form})
    def get(self,request):
        form = self.form_class()
        return render(request,self.template_name,{'form':form})
class UserLogoutView(LoginRequiredMixin,View):
    login_url='/accounts/login/'
    def get(self,request):
        logout(request)
        messages.success(request,'your account logged out successfully:)))','success')
        return redirect('home:home')
class UserProfileView(LoginRequiredMixin,View):
    def get(self,request,user_id):
        user = User.objects.get(id = user_id)
        is_following=False
        relation = Relation.objects.filter(from_user=request.user,to_user=user)
        if relation.exists():
            is_following=True
        posts = user.posts.all()
        return render(request,'accounts/profile.html',{'user':user , 'posts':posts,'is_following':is_following})
class UserPasswordResetView(auth_view.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'
class UserPasswordResetDoneView(auth_view.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'
class UserPasswordResetConfirmView(auth_view.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')
class UserPasswordResetCompleteView(auth_view.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'
class UserFollowView(LoginRequiredMixin,View):
    def get(self,request,user_id):
        relation = Relation.objects.filter(from_user = request.user,to_user=User.objects.get(id=user_id))
        if relation.exists():
            messages.error(request,'already you have followed','danger')
        else:
            Relation(from_user = request.user,to_user=User.objects.get(id=user_id)).save()
            messages.success(request,'you followed successfully','success')
        return redirect('accounts:profile' , user_id)
    

class UserUnfollowView(LoginRequiredMixin,View):
    def get(self,request,user_id):
        user = User.objects.get(id=user_id)
        relation = Relation.objects.filter(from_user=request.user,to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request,'this user unfollowed successfully','success')
        else:
            messages.error(request,'you didn\'t follow this user yet','danger')
        return redirect('accounts:profile', user_id)

class EditProfileView(LoginRequiredMixin,View):
    form_class = forms.EditProfileForm

    def get(self,request):
        form = self.form_class(instance = request.user.profile,initial = {'email':request.user.email})
        return render(request,'accounts/edit_profile.html',{'form':form})
    def post(self,request):
        form = self.form_class(request.POST,instance = request.user.profile,initial = {'email':request.user.email})
        if form.is_valid():
            form.save()
            request.user.email = form.cleaned_data['email']
            request.user.save()
            messages.success(request,'your profile edited successfully','success')
        return redirect('accounts:profile', request.user.id)
        
        


A/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}



{% block content %}
    <form action="" method ='post'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Edit">
    </form>
{% endblock content %}
    

A/accounts/templates/accounts/login.html
{% extends 'base.html' %}


{% block content %}
    <h3>Login User</h3>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="login">
    </form>
{% endblock content %}
    

A/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}



{% block content %}
    <p>password changed successfully.</p>
{% endblock content %}
    

A/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}



{% block content %}
    
    {% if validlink %} 
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Change">
    </form>
    {% else %}
        <p>this link is not valid please try again</p>
    {% endif %}
{% endblock content %}
    

A/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}



{% block content %}
    <p>we sent you an email</p>
{% endblock content %}
    

A/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

A/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}



{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Send">
    </form>
{% endblock content %}
    

A/accounts/templates/accounts/profile.html
{% extends 'base.html' %}



{% block content %}

{% if request.user.id == user.id %}
    <a href="{% url 'home:create'  %}" class="btn btn-success">Create</a>
    <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">EditProfile</a>
{% endif %}
{% if request.user.id != user.id %}
    {% if is_following %}
    <a href="{% url 'accounts:unfollow' user.id  %}" class="btn btn-danger">Unfollow</a>
    {% else %}
    <a href="{% url 'accounts:follow' user.id  %}" class="btn btn-info">Follow</a>
    {% endif %}


{% endif %}
    

<html lang="en">
<head>
    <h2 class="text-center">{{user.username}}</h2>
</head>
<body>
    {% for post in posts %}
   <a href="{{ post.get_absolute_url }}"> {{post.body|truncatewords:3 }}</a>
   <br>
    {% endfor %}
</body>
</html>
    
{% endblock content %}
    

A/accounts/templates/accounts/register.html
{% extends 'base.html' %}
<html lang="en">


{% block content %}
    

    

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <h2>Register User</h2>
</head>
<body>
    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Register">
    </form>
    
</body>
{% endblock content %}
</html>