A/A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]

A/accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/',views.UserFollowView.as_view(), name= 'follow'),
    path('unfollow/<int:user_id>/  ', views.UserUnfollowView.as_view(), name = 'unfollow'),
    path('editprofile/',views.EditProfileView.as_view(),name = 'edit_profile'),
]

A/home/urls.py
from django.urls import path
from . import views



app_name='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name='home'),
    path('post/<int:post_id>/<slug:post_slug>/',views.PostView.as_view(),name='detail'),
    path('post/delete/<int:post_id>/<slug:post_slug>/',views.DeletePostView.as_view(),name='delete'),
    path('post/update/<int:post_id>/',views.UpdatePostView.as_view(),name='update'),
    path('post/create/',views.CreatePostView.as_view(),name='create'),
    path('reply/<int:post_id>/<int:comment_id>/',views.ReplyPostView.as_view(),name = 'add_reply'),
    path('like/<int:post_id>/',views.LikePostView.as_view(),name = 'like_post'),
]

A/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f'{self.slug} - {self.created}'
    def get_absolute_url(self):
        return reverse('home:detail', args=[self.id , self.slug])
    def like_count(self):
        return self.pvote.count()
    def user_can_like(self,user):
        if self.pvote.filter(user=user).exists():
            return True
        return False
    
class Comment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='ucomment')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='pcomment')
    reply = models.ForeignKey('self',on_delete=models.CASCADE,related_name='rcomment',null=True,blank=True)
    is_reply = models.BooleanField(default=False)
    body = models.CharField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} posted {self.body[:30]}'
    
class Vote(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='uvote')
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='pvote')

    def __str__(self):
        return f'{self.user} liked {self.post.slug[:10]}'
        

A/home/forms.py
from django import forms
from .models import Post, Comment

class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)

class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }

class PostSearchForm(forms.Form):
    search = forms.CharField(required=False)

A/home/views.py
from typing import Any
from django.http.request import HttpRequest as HttpRequest
from django.shortcuts import render,redirect,get_object_or_404
from django.views import View
from .models import Post,Comment,Vote
from django.contrib import messages
from .forms import PostCreateUpdateForm , PostCommentForm , CommentReplyForm , PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    form_class = PostSearchForm

    def get(self,request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__contains=request.GET['search'])
        return render(request,'home/index.html',{'posts':posts,'form':self.form_class})
    
    
class PostView(View):
    form_class = PostCommentForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)
    
    def get(self, request, *args , **kwargs):
        can_like = False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like = True
        comments = self.post_instance.pcomment.filter(is_reply=False)
        return render(request, 'home/detail.html', {'post': self.post_instance, 'comments': comments,'form':self.form_class(),'reply_form':self.form_class_reply(),'can_like':can_like})
    
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request,'your comment submitted successfully','success')
            return redirect('home:detail',self.post_instance.id , self.post_instance.slug)
    
class DeletePostView(LoginRequiredMixin,View):

    def get(self,request,post_id,post_slug):
        post=get_object_or_404(Post,pk=post_id,slug=post_slug)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request,'your post deleted successfully','success')
        else:
            messages.error(request,'you cant delete this file','danger')
        return redirect('home:home')
    

class UpdatePostView(LoginRequiredMixin,View):
    form_class = PostCreateUpdateForm
    template_name = 'home/update.html'

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post,pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = Post.objects.get()
        if not request.user.id == post.user.id:
            messages.error(request, 'You can\'t update this post', 'danger')
            return redirect('home:home') 
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)  
        return render(request, self.template_name, {'form': form, 'post': post})

    def post(self,request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST,instance=post)  
        if form.is_valid():
            post=form.save(commit=False)
            post.slug=slugify(form.cleaned_data['body'][:30])
            post.save()
            messages.success(request,'your post updated successfully','success')
        return redirect('home:detail',post.id,post.slug)
    

class CreatePostView(LoginRequiredMixin,View):
    form_class = PostCreateUpdateForm
    def get(self,request):
        form = self.form_class()
        return render(request,'home/create.html',{'form':form})
    
    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.user = request.user
            new_post.save()
            messages.success(request,'your post created successfully','success')
            return redirect('home:detail',new_post.id,new_post.slug)

class ReplyPostView(LoginRequiredMixin,View):
    form_class = CommentReplyForm
    
    def post(self,request,post_id,comment_id):
        form = self.form_class(request.POST)
        post = get_object_or_404(Post,id = post_id)
        comment = get_object_or_404(Comment,id = comment_id)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request,'your reply submitted successfully','success')
        return redirect('home:detail', post.id,post.slug)

class LikePostView(LoginRequiredMixin,View):
    
    def get(self,request,post_id):
        post = get_object_or_404(Post,id=post_id)
        like = Vote.objects.filter(post=post,user=request.user)
        if like.exists():
            messages.error(request,'you liked this post befor','danger')
        else:
            Vote.objects.create(post=post,user=request.user)
            messages.success(request,'you liked this post','success')
        return redirect('home:detail',post.id,post.slug)

A/home/templates/home/create.html
{% extends 'base.html' %}



{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock content %}

A/home/templates/home/detail.html
{% extends 'base.html' %}





<html lang="en">
{% block content %}
<head>
    
    <a href="{% url 'accounts:profile' post.user.id %}">{{post.user.username}}</a> - {{post.updated|date:"Y-M"}}
    
</head>
<br>
<body>
    <br>
    {% if request.user.id == post.user.id %}
    <a href="{% url 'home:delete' post.id post.slug %}" class="btn btn-danger">Delete</a>
    <a href="{% url 'home:update' post.id %}" class="btn btn-info">Update</a>
    {% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'home:like_post' post.id  %}" class=" {% if can_like %}disabled{% endif %} btn btn-primary col-md-2">Like{{post.like_count}}</a>
        
    {% endif %}
    <p>{{post.body}}</p></hr>
    {% if request.user.is_authenticated %}
        <form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Comment">
        </form><br/>
    {% endif %}
    

    {% for comment in comments %}
        <div class="card">
            <p class="card-header">{{comment.user}} | {{comment.created|timesince}} ago</p>
            <p class="card-body">{{comment.body}}</p>
            
            {% if request.user.is_authenticated %}    
            <form action="{% url 'home:add_reply' post.id comment.id %}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="reply">
            </form>
            {% endif %}
            {% with replies=comment.rcomment.all %}
            {% for reply in replies %}
                <p class="bg-primary p-3 m-2">{{reply.user}} <br/> {{reply.body}} </p>
            {% empty %}
            {% endfor %}
            {% endwith %}
        </div>
        <br/>
    {% empty %}
        <p>No comments yet!</p>
    {% endfor %}
</body>
{% endblock content %}
</html>

A/home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}

<html lang="en">

<head>
    <form action="" method="get">
        {{form.as_p}}
        <input type="submit" value="search">
    </form>
</head>
<div class="card">
    {%for post in posts%}
    <a href="{{ post.get_absolute_url }}" class="card-body">{{post.body|truncatewords:1 }}</a>
    <br>
    {% endfor %}
</div>
{% endblock content %}
</html>

A/home/templates/home/update.html
{% extends 'base.html' %}



{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}